//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NubeBooks.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleOrdenCompra
    {
        public int IdDetalleOrdenCompra { get; set; }
        public int IdOrdenCompra { get; set; }
        public int IdItem { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioUnidad { get; set; }
        public decimal MontoTotal { get; set; }
        public decimal PorcentajeIgv { get; set; }
        public decimal Igv { get; set; }
        public string UnidadMedida { get; set; }
        public string ItemServicio { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual OrdenCompra OrdenCompra { get; set; }
    }
}
