
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NubeBooks.Data
{

using System;
    using System.Collections.Generic;
    
public partial class DetalleProforma
{

    public int IdDetalleProforma { get; set; }

    public int IdProforma { get; set; }

    public int IdItem { get; set; }

    public int Cantidad { get; set; }

    public decimal PrecioUnidad { get; set; }

    public Nullable<decimal> Descuento { get; set; }

    public Nullable<decimal> MontoTotal { get; set; }

    public Nullable<decimal> TipoCambio { get; set; }

    public Nullable<decimal> PorcentajeIgv { get; set; }

    public Nullable<decimal> Igv { get; set; }

    public string UnidadMedida { get; set; }

    public Nullable<decimal> PorcentajeDescuento { get; set; }

    public string ItemServicio { get; set; }



    public virtual Item Item { get; set; }

    public virtual Proforma Proforma { get; set; }

}

}
