//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NubeBooks.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenCompra()
        {
            this.DetalleOrdenCompra = new HashSet<DetalleOrdenCompra>();
        }
    
        public int IdOrdenCompra { get; set; }
        public string CodigoOrdenCompra { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdEmpresa { get; set; }
        public int IdProveedor { get; set; }
        public Nullable<int> IdContacto { get; set; }
        public int IdMoneda { get; set; }
        public string Consideraciones { get; set; }
        public int AprobadoPor { get; set; }
        public bool IncluirFirma { get; set; }
        public string Comentario { get; set; }
    
        public virtual Contacto Contacto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleOrdenCompra> DetalleOrdenCompra { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual EntidadResponsable EntidadResponsable { get; set; }
        public virtual Moneda Moneda { get; set; }
    }
}
